# Generated by Django 4.2.5 on 2023-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(unique=True, upload_to='', verbose_name='File')),
                ('file_content', models.CharField(editable=False, max_length=10000, null=True)),
            ],
        ),
    ]
